// Generated by scripts/optimize-portal-first-paint.mjs. Do not edit by hand.
// Mirrors the portalQuery literal in app/SchoolLearningPortal.tsx so the server
// prefetch in lib/sanity/portal.ts stays byte-for-byte identical to the query
// the browser uses for its live refresh.

export const PORTAL_QUERY = `
  *[_type == "grade" && isActive != false] | order(order asc, gradeNumber asc) {
    _id,
    title,
    "gradeNumber": coalesce(gradeNumber, order),
    "slug": slug.current,
    "shortDescription": coalesce(shortDescription, description),
    icon,
    "subjects": *[_type == "subject" && grade._ref == ^._id && isActive != false]
      | order(order asc, title asc) {
        _id,
        title,
        "slug": slug.current,
        "shortDescription": coalesce(shortDescription, description),
        emoji,
        cardIllustration {
          alt,
          crop,
          hotspot,
          "asset": asset->{url}
        },
        "chapters": *[_type == "chapter" && subject._ref == ^._id && isActive != false]
          | order(order asc, title asc) {
            _id,
            title,
            "slug": slug.current,
            "summary": coalesce(summary, description),
            coverImage { alt, "asset": asset->{url} },
            chapterImage {
              alt,
              crop,
              hotspot,
              "asset": asset->{url}
            },
            "lessons": *[_type == "lesson" && chapter._ref == ^._id && isActive != false]
              | order(order asc, title asc) {
                _id,
                title,
                "slug": slug.current,
                "summary": coalesce(summary, description),
                coverImage { alt, "asset": asset->{url} },
                "flashcardCount": count(flashcards[isActive != false])
              }
          }
      }
  }
`;
